---
- hosts: smart-clock
  tasks:
    - name: Install lighttpd
      apt:
        name: lighttpd
        state: present
    - name: Install RaspAP
      command: curl -sL https://install.raspap.com | bash -s -- --yes --openvpn 0 --adblock 0 --cert
    - name: Reboot
      shell: reboot
      async: 10
      poll: 0
    - name: Wait for reboot
      wait_for_connection:
        delay: 10
