name: Rust

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install ARM compiler
        run: sudo apt-get install g++-10-multilib-arm-linux-gnueabihf
      - name: Add rustup ARM target
        run: rustup target add armv7-unknown-linux-gnueabihf
      - name: Build
        run: cargo build --verbose
